### ISSUE TITLE
signing `msgEthereumTx`  fails

### ISSUE THREAD

**Issue by danburck** [evmos/ethermint#1271] opened 2022-08-15 16:11 UTC
## Problem

A msg validation was introduced to prevent setting the From address for `msgEthereumTx` [here](https://github.com/evmos/ethermint/pull/1176/files#diff-52b9d2ef0613ce4a83599b343d4d05f67985e4cfb071fee3f70154ca873813c4R435-R438). With the current signing function this will make every `msgEthereumTx` fail, see [here](https://github.com/evmos/ethermint/blob/main/x/evm/types/msg.go#L242-L244).

**Comment by facs95** [comment] 2022-08-15 16:43
Closing this issue since it's not an issue but intended behavior

**Closed by facs95** 2022-08-15 16:43 UTC
Labels: 🐛 High
